format = """
$time\

[](fg:#33658A)\

[](#33658A)\

$username\

[>](bg:#00000 fg:#0DC28C)\

$directory\

[>](fg:#0DC28C bg:#00000)\
"""
# $git_branch\

# $git_status\

# [â†’](fg:#FCA17D bg:#86BBD8)\

# $c\

# $elixir\

# $elm\

# $golang\

# $haskell\

# $java\

# $julia\

# $nodejs\

# $nim\

# $rust\

# [â†’](fg:#86BBD8 bg:#06969A)\

# $docker_context\

# [â†’](fg:#06969A bg:#33658A)\

# $time\

# [â†’ ](fg:#33658A)\

# """

 

# Disable the blank line at the start of the prompt

# add_newline = false

 

# You can also replace your username with a neat symbol like ï„  to save some space

[username]

show_always = true

style_user = "bg:#3087FB"

style_root = "bg:#3087FB"

format = '[Î» $user]($style)'
# â€ºÂ»
 

[directory]

style = "bg:#33658A"

format = "[[$path](fg:#0DC28C)]($style)"

truncation_length = 3

truncation_symbol = "â€¦/"

 
[time]

disabled = false

time_format = "%R" # Hour:Minute Format

style = "bg:#33658A"

format = '[[$time ](fg:#0DC28C)]($style)'

# Here is how you can shorten some long paths by text replacement

# similar to mapped_locations in Oh My Posh:

[directory.substitutions]

"Documents" = "Docs "

"Downloads" = "Down "

# "Music" = "ğŸœ "

"Pictures" = "Pics "


# Keep in mind that the order matters. For example:

# "Important Documents" = " ïœ˜ï„ª "

# will not be replaced, because "Documents" was already substituted before.

# So either put "Important Documents" before "Documents" or use the substituted version:

# "Important ïœ˜ " = " ïœ˜ï„ª "

 

# [c]

# symbol = "Â© "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [docker_context]

# symbol = "ğŸ³ "

# style = "bg:#06969A"

# format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

 

# [elixir]

# symbol = "ğŸ’§ "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [elm]

# symbol = "ğŸŒ³ "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [git_branch]

# symbol = "â˜Š"

# style = "bg:#FCA17D"

# format = '[[ $symbol $branch ](bg:#FCA17D)]($style)'

 

# [git_status]

# style = "bg:#FCA17D"

# format = '[[($all_status$ahead_behind )](bg:#FCA17D)]($style)'

 

# [golang]

# symbol = "ğŸ¹ "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [haskell]

# symbol = "Î» "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [java]

# symbol = "â˜• "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [julia]

# symbol = "à®ƒ "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [nodejs]

# symbol = "ğŸ”· "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [nim]

# symbol = "ğŸ‘‘ "

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

 

# [rust]

# symbol = "ğŸ¦€"

# style = "bg:#86BBD8"

# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

